config:
  validation: true
  warningsAsErrors: true

comments:
  active: false

complexity:
  severity: warning
  ComplexCondition:
    severity: error
  CyclomaticComplexMethod:
    allowedComplexity: 15
  NestedBlockDepth:
    severity: error
  TooManyFunctions:
    active: false

coroutines:
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    excludes:
      - '**/coroutines/DispatcherProvider.kt'
  SuspendFunInFinallySection:
    active: true
  SuspendFunSwallowedCancellation:
    active: true

exceptions:
  TooGenericExceptionThrown:
    severity: warning
  ErrorUsageWithThrowable:
    active: true
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true

potential-bugs:
  CastNullableToNonNullableType:
    active: true
  CastToNullableType:
    active: true
  CharArrayToStringCall:
    active: true
  DontDowncastCollectionTypes:
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ModifierOrder:
    active: false
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    severity: warning
  ThrowsCount:
    severity: warning
  UnusedPrivateFunction:
    allowedNames: '.*Preview'
  UnusedPrivateProperty:
    active: true
  WildcardImport:
    active: false

naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
